// generated by @/scripts/generate-wrangler-config.ts

export const MAX_QUEUE_JOB_DELIVERY_ATTEMPTS_BY_ENV = {
  development: 6,
  production: 6,
} as const;

export type WorkerEnvironment =
  keyof typeof MAX_QUEUE_JOB_DELIVERY_ATTEMPTS_BY_ENV;

export function getMaxQueueJobDeliveryAttempts(env: {
  ENV: WorkerEnvironment;
}) {
  return MAX_QUEUE_JOB_DELIVERY_ATTEMPTS_BY_ENV[env.ENV];
}
