export const AUDD_CHUNK_DURATION_MS = 12000;

export const AUDD_SCAN_EVERY_CHUNKS = 1;

export const AUDD_SCAN_SKIP_CHUNKS = 0;

export const AUDD_SCAN_INTERVAL_MS =
  AUDD_CHUNK_DURATION_MS * (AUDD_SCAN_EVERY_CHUNKS + AUDD_SCAN_SKIP_CHUNKS);
