import { COLORS } from '@/theme/base';
import { execFileSync } from 'child_process';
import chroma from 'chroma-js';
import fs from 'fs';
import path from 'path';
import { createLogger } from './logger';
import * as tokens from '@/theme/tokens';

const themePath = (...segments: string[]) =>
  path.join(process.cwd(), 'theme', ...segments);

function parseOKLCH(oklchStr: string): {
  l: number;
  c: number;
  h: number;
  a?: string;
} {
  const match = oklchStr.match(/oklch\(([^)]+)\)/);
  if (!match) throw new Error('Invalid OKLCH: ' + oklchStr);
  const parts = match[1].split('/').map((s) => s.trim());
  const [l, c, h] = parts[0].split(/\s+/).map(Number);
  const a = parts[1] ? parts[1] : undefined;
  return { l, c, h, a };
}

function oklchToHSLStr(oklchStr: string): string {
  const { l, c, h, a } = parseOKLCH(oklchStr);
  const hsl = chroma.oklch(l, c, h).hsl();
  let hVal = Math.round(hsl[0]);
  let sVal = Math.round(hsl[1] * 100);
  let lVal = Math.round(hsl[2] * 100);
  if (isNaN(hVal)) hVal = 0;
  if (isNaN(sVal)) sVal = 0;
  if (isNaN(lVal)) lVal = 0;

  if (sVal === 0 || lVal === 0 || lVal === 100) {
    hVal = 0;
    sVal = 0;
  }

  if (a) return `${hVal} ${sVal}% ${lVal}% / ${a}`;
  return `${hVal} ${sVal}% ${lVal}%`;
}

function genCSSVars(theme: Record<string, string>) {
  let css = '';

  for (const [key, value] of Object.entries(theme)) {
    const varName = `--${key.replace(/([A-Z])/g, '-$1').toLowerCase()}`;
    css += `${varName}:${oklchToHSLStr(value)};`;
  }

  return css;
}

function toThemeVarName(key: string) {
  return key.replace(/([A-Z])/g, '-$1').toLowerCase();
}

function getSpectrumVariants(oklchStr: string) {
  const { l, c, h } = parseOKLCH(oklchStr);

  return {
    lighter: `hsl(${oklchToHSLStr(`oklch(${Math.min(l + 0.075, 1)} ${c} ${h})`)})`,
    default: `hsl(${oklchToHSLStr(oklchStr)})`,
    darker: `hsl(${oklchToHSLStr(`oklch(${Math.max(l - 0.075, 0)} ${c} ${h})`)})`,
  };
}

function generateTailwindTheme() {
  const uiTheme = Object.keys(COLORS.light.ui).map((key) => {
    const varName = toThemeVarName(key);
    return `--color-${varName}: hsl(var(--${varName}));`;
  });

  const spectrumTheme = (['light', 'dark'] as const).flatMap((mode) =>
    COLORS[mode].spectrum.flatMap((color, colorIndex) =>
      Object.entries(getSpectrumVariants(color)).map(
        ([variant, value]) =>
          `--color-spectrum-${mode}-${colorIndex}-${variant}: ${value};`
      )
    )
  );

  return [
    ...uiTheme,
    ...spectrumTheme,
    `--radius: ${tokens.RADII.DEFAULT};`,
    `--radius-xs: ${tokens.RADII.xs};`,
    `--radius-sm: ${tokens.RADII.sm};`,
    `--radius-md: ${tokens.RADII.md};`,
    `--radius-lg: ${tokens.RADII.lg};`,
    `--radius-xl: ${tokens.RADII.xl};`,
    `--radius-2xl: ${tokens.RADII['2xl']};`,
    `--radius-3xl: ${tokens.RADII['3xl']};`,
    `--radius-4xl: ${tokens.RADII['4xl']};`,
    `--container-sheet: ${tokens.CONTAINERS.sheet};`,
    `--text-2xs: ${tokens.FONT_SIZES['2xs']};`,
    `--spacing-avatar-stack-sm: ${tokens.SPACING.avatarStackSm};`,
    `--spacing-avatar-stack-sm-overlap: ${tokens.SPACING.avatarStackSmOverlap};`,
    `--spacing-avatar-stack-lg: ${tokens.SPACING.avatarStackLg};`,
    `--spacing-avatar-stack-lg-overlap: ${tokens.SPACING.avatarStackLgOverlap};`,
    `--spacing-action-menu-nudge: ${tokens.SPACING.actionMenuNudge};`,
    `--breakpoint-2xs: ${tokens.BREAKPOINTS['2xs']};`,
    `--breakpoint-xs: ${tokens.BREAKPOINTS.xs};`,
    `--breakpoint-sm: ${tokens.BREAKPOINTS.sm};`,
    `--breakpoint-md: ${tokens.BREAKPOINTS.md};`,
    `--breakpoint-lg: ${tokens.BREAKPOINTS.lg};`,
    `--breakpoint-xl: ${tokens.BREAKPOINTS.xl};`,
    `--breakpoint-2xl: ${tokens.BREAKPOINTS['2xl']};`,
  ].join('\n  ');
}

function generateThemeCSS() {
  const lightVars = genCSSVars(COLORS.light.ui);
  const darkVars = genCSSVars(COLORS.dark.ui);
  const theme = generateTailwindTheme();
  return `/* generated by @/scripts/assets.ts */\n\n@theme inline {\n  ${theme}\n}\n\n@layer theme {\n  :root {\n    @variant light {\n      ${lightVars}\n    }\n\n    @variant dark {\n      ${darkVars}\n    }\n  }\n}`;
}

function generateSpectrumTS() {
  const spectrum: Record<string, ReturnType<typeof getSpectrumVariants>[]> = {
    light: [],
    dark: [],
  };

  for (const mode of ['light', 'dark'] as const) {
    const modeColors = COLORS[mode] as typeof COLORS.light;

    for (const [key, value] of modeColors.spectrum.entries()) {
      spectrum[mode][key] = getSpectrumVariants(value as string);
    }
  }

  return `// generated by @/scripts/assets.ts\n\nexport const SPECTRUM=${JSON.stringify(spectrum)} as const;\n\ntype ToNumber<T>=T extends \`${'${'}infer N extends number${'}'}\` ? N : never;\ntype SpectrumIndex=Extract<keyof typeof SPECTRUM.light,\`${'${'}number${'}'}\`>;\n\nexport type Color=ToNumber<SpectrumIndex>;\n\nexport const DEFAULT_SPECTRUM_COLOR=11 satisfies Color;\n\nexport function isColor(value:unknown):value is Color{return typeof value==='number'&&Number.isInteger(value)&&value>=0&&value<SPECTRUM.light.length;}\n\nexport function resolveSpectrumColor(value:unknown,fallback:Color=DEFAULT_SPECTRUM_COLOR):Color{return isColor(value)?value:fallback;}`;
}

function getSpectrumClassName({
  colorIndex,
  darkVariant,
  lightVariant,
  property,
  statePrefix,
}: {
  colorIndex: number;
  darkVariant: 'lighter' | 'default' | 'darker';
  lightVariant: 'lighter' | 'default' | 'darker';
  property: 'bg' | 'border' | 'text';
  statePrefix?: string;
}) {
  const prefix = statePrefix ? `${statePrefix}:` : '';
  return `${prefix}${property}-spectrum-light-${colorIndex}-${lightVariant} dark:${prefix}${property}-spectrum-dark-${colorIndex}-${darkVariant}`;
}

function renderSpectrumClassNameSwitch(
  renderClassName: (colorIndex: number) => string
) {
  const colorIndexes = COLORS.light.spectrum.map((_, index) => index);
  const fallbackIndex = colorIndexes.at(-1) ?? 0;

  const cases = colorIndexes
    .slice(0, -1)
    .map(
      (colorIndex) =>
        `case ${colorIndex}:return '${renderClassName(colorIndex)}';`
    )
    .join('');

  return `switch(resolveColor(color)){${cases}default:return '${renderClassName(fallbackIndex)}';}`;
}

function renderSpectrumClassNameFunction({
  darkVariant,
  lightVariant,
  name,
  property,
  statePrefix,
}: {
  darkVariant: 'lighter' | 'default' | 'darker';
  lightVariant: 'lighter' | 'default' | 'darker';
  name: string;
  property: 'bg' | 'border' | 'text';
  statePrefix?: string;
}) {
  return `export function ${name}(color:unknown){${renderSpectrumClassNameSwitch((colorIndex) => getSpectrumClassName({ colorIndex, darkVariant, lightVariant, property, statePrefix }))}}`;
}

function generateSpectrumClassNamesTS() {
  const getSwatchBackgroundClassName = renderSpectrumClassNameSwitch(
    (colorIndex) =>
      getSpectrumClassName({
        colorIndex,
        darkVariant: 'darker',
        lightVariant: 'lighter',
        property: 'bg',
      })
  );

  const getSwatchBorderClassName = renderSpectrumClassNameSwitch((colorIndex) =>
    getSpectrumClassName({
      colorIndex,
      darkVariant: 'lighter',
      lightVariant: 'darker',
      property: 'border',
    })
  );

  return `// generated by @/scripts/assets.ts\n\nimport { DEFAULT_SPECTRUM_COLOR, isColor } from '@/theme/spectrum';\n\nfunction resolveColor(color:unknown){return isColor(color)?color:DEFAULT_SPECTRUM_COLOR;}\n\n${renderSpectrumClassNameFunction({ name: 'getSpectrumBackgroundClassName', property: 'bg', lightVariant: 'default', darkVariant: 'default' })}\n\n${renderSpectrumClassNameFunction({ name: 'getSpectrumHoverBackgroundClassName', property: 'bg', lightVariant: 'default', darkVariant: 'default', statePrefix: 'web:hover' })}\n\n${renderSpectrumClassNameFunction({ name: 'getSpectrumActiveBackgroundClassName', property: 'bg', lightVariant: 'default', darkVariant: 'default', statePrefix: 'active' })}\n\nexport function getSpectrumInteractiveBackgroundClassName(color:unknown){return [getSpectrumHoverBackgroundClassName(color),getSpectrumActiveBackgroundClassName(color)].join(' ');}\n\n${renderSpectrumClassNameFunction({ name: 'getSpectrumBorderClassName', property: 'border', lightVariant: 'default', darkVariant: 'default' })}\n\n${renderSpectrumClassNameFunction({ name: 'getSpectrumTextClassName', property: 'text', lightVariant: 'default', darkVariant: 'default' })}\n\n${renderSpectrumClassNameFunction({ name: 'getSpectrumDarkerTextClassName', property: 'text', lightVariant: 'darker', darkVariant: 'darker' })}\n\n${renderSpectrumClassNameFunction({ name: 'getSpectrumAccentBackgroundClassName', property: 'bg', lightVariant: 'darker', darkVariant: 'lighter' })}\n\n${renderSpectrumClassNameFunction({ name: 'getSpectrumAccentTextClassName', property: 'text', lightVariant: 'darker', darkVariant: 'lighter' })}\n\nexport function getSpectrumSwatchBackgroundClassName(color:unknown,selected:boolean){if(!selected)return getSpectrumBackgroundClassName(color);${getSwatchBackgroundClassName}}\n\nexport function getSpectrumSwatchBorderClassName(color:unknown,selected:boolean){if(!selected)return getSpectrumBorderClassName(color);${getSwatchBorderClassName}}`;
}

function generateUITS() {
  const ui: Record<string, Record<string, string>> = { light: {}, dark: {} };

  for (const mode of ['light', 'dark'] as const) {
    const modeColors = COLORS[mode] as typeof COLORS.light;

    for (const [key, value] of Object.entries(modeColors.ui)) {
      ui[mode][key] = `hsl(${oklchToHSLStr(value as string)})`;
    }
  }

  return `// generated by @/scripts/assets.ts\n\nexport const UI=${JSON.stringify(ui)};\n\nexport type UIColor=keyof typeof UI.light;`;
}

const outputPaths = [
  { path: themePath('generated.css'), render: generateThemeCSS },
  { path: themePath('spectrum.ts'), render: generateSpectrumTS },
  {
    path: themePath('spectrum-class-names.ts'),
    render: generateSpectrumClassNamesTS,
  },
  { path: themePath('ui.ts'), render: generateUITS },
] as const;

export function generateTheme() {
  const { log, progress } = createLogger('generate-theme');
  fs.mkdirSync(themePath(), { recursive: true });
  log(`Writing ${outputPaths.length} theme outputs`);

  for (const [index, output] of outputPaths.entries()) {
    fs.writeFileSync(output.path, output.render());
    progress(`Theme ${index + 1}/${outputPaths.length}: ${output.path}`);
  }

  log('Formatting generated theme files');

  const formatOutput = execFileSync(
    'bun',
    [
      'scripts/format.ts',
      ...outputPaths.map((output) => path.relative(process.cwd(), output.path)),
    ],
    { encoding: 'utf8' }
  );

  for (const line of formatOutput.split('\n')) {
    const trimmedLine = line.trim();
    if (trimmedLine.length > 0) progress(trimmedLine);
  }

  log('Done');
}
