// generated by @/scripts/generate-theme.ts

import { DarkTheme, DefaultTheme } from '@react-navigation/native';

export const NAVIGATION = Object.freeze({
  light: {
    ...DefaultTheme,
    colors: {
      ...DefaultTheme.colors,
      background: 'hsl(0 0% 90%)',
      card: 'hsl(0 0% 90%)',
    },
  },

  dark: {
    ...DarkTheme,
    colors: {
      ...DarkTheme.colors,
      background: 'hsl(0 0% 5%)',
      card: 'hsl(0 0% 5%)',
    },
  },
});
