// generated by @/scripts/generate-theme.ts

import { DarkTheme, DefaultTheme } from '@react-navigation/native';

export const NAVIGATION = Object.freeze({
  light: {
    ...DefaultTheme,
    colors: {
      ...DefaultTheme.colors,
      background: 'rgb(235, 235, 235)',
      card: 'rgb(235, 235, 235)',
      border: 'rgba(0, 0, 0, 0.06)',
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      ...DarkTheme.colors,
      background: 'rgb(18, 18, 18)',
      card: 'rgb(18, 18, 18)',
      border: 'rgba(255, 255, 255, 0.05)',
    },
  },
});
