// generated by @/scripts/generate-theme.ts

export const SPECTRUM = {
  light: [
    {
      lighter: 'hsl(341 42% 64%)',
      default: 'hsl(341 32% 55%)',
      darker: 'hsl(340 31% 46%)',
    },
    {
      lighter: 'hsl(8 48% 63%)',
      default: 'hsl(8 37% 53%)',
      darker: 'hsl(8 37% 44%)',
    },
    {
      lighter: 'hsl(27 49% 55%)',
      default: 'hsl(28 47% 46%)',
      darker: 'hsl(29 58% 37%)',
    },
    {
      lighter: 'hsl(44 41% 48%)',
      default: 'hsl(45 51% 39%)',
      darker: 'hsl(46 73% 29%)',
    },
    {
      lighter: 'hsl(119 24% 54%)',
      default: 'hsl(119 24% 46%)',
      darker: 'hsl(120 28% 37%)',
    },
    {
      lighter: 'hsl(170 45% 46%)',
      default: 'hsl(171 62% 36%)',
      darker: 'hsl(172 100% 24%)',
    },
    {
      lighter: 'hsl(191 51% 49%)',
      default: 'hsl(190 70% 38%)',
      darker: 'hsl(190 100% 28%)',
    },
    {
      lighter: 'hsl(212 55% 62%)',
      default: 'hsl(211 43% 53%)',
      darker: 'hsl(211 46% 44%)',
    },
    {
      lighter: 'hsl(246 43% 69%)',
      default: 'hsl(247 32% 59%)',
      darker: 'hsl(247 25% 50%)',
    },
    {
      lighter: 'hsl(295 29% 62%)',
      default: 'hsl(295 23% 53%)',
      darker: 'hsl(295 24% 44%)',
    },
    {
      lighter: 'hsl(18 20% 60%)',
      default: 'hsl(18 16% 51%)',
      darker: 'hsl(18 18% 42%)',
    },
    {
      lighter: 'hsl(0 0% 59%)',
      default: 'hsl(0 0% 50%)',
      darker: 'hsl(0 0% 42%)',
    },
  ],
  dark: [
    {
      lighter: 'hsl(341 42% 64%)',
      default: 'hsl(341 32% 55%)',
      darker: 'hsl(340 31% 46%)',
    },
    {
      lighter: 'hsl(8 48% 63%)',
      default: 'hsl(8 37% 53%)',
      darker: 'hsl(8 37% 44%)',
    },
    {
      lighter: 'hsl(27 49% 55%)',
      default: 'hsl(28 47% 46%)',
      darker: 'hsl(29 58% 37%)',
    },
    {
      lighter: 'hsl(44 41% 48%)',
      default: 'hsl(45 51% 39%)',
      darker: 'hsl(46 73% 29%)',
    },
    {
      lighter: 'hsl(119 24% 54%)',
      default: 'hsl(119 24% 46%)',
      darker: 'hsl(120 28% 37%)',
    },
    {
      lighter: 'hsl(170 45% 46%)',
      default: 'hsl(171 62% 36%)',
      darker: 'hsl(172 100% 24%)',
    },
    {
      lighter: 'hsl(191 51% 49%)',
      default: 'hsl(190 70% 38%)',
      darker: 'hsl(190 100% 28%)',
    },
    {
      lighter: 'hsl(212 55% 62%)',
      default: 'hsl(211 43% 53%)',
      darker: 'hsl(211 46% 44%)',
    },
    {
      lighter: 'hsl(246 43% 69%)',
      default: 'hsl(247 32% 59%)',
      darker: 'hsl(247 25% 50%)',
    },
    {
      lighter: 'hsl(295 29% 62%)',
      default: 'hsl(295 23% 53%)',
      darker: 'hsl(295 24% 44%)',
    },
    {
      lighter: 'hsl(18 20% 60%)',
      default: 'hsl(18 16% 51%)',
      darker: 'hsl(18 18% 42%)',
    },
    {
      lighter: 'hsl(0 0% 59%)',
      default: 'hsl(0 0% 50%)',
      darker: 'hsl(0 0% 42%)',
    },
  ],
};

export type Color = keyof typeof SPECTRUM.light;
