// generated by @/scripts/generate-theme.ts

export const SPECTRUM = {
  light: [
    {
      lighter: 'hsl(340 100% 77%)',
      default: 'hsl(339 71% 68%)',
      darker: 'hsl(339 53% 58%)',
    },
    {
      lighter: 'hsl(8 100% 74%)',
      default: 'hsl(8 79% 66%)',
      darker: 'hsl(7 60% 57%)',
    },
    {
      lighter: 'hsl(29 95% 63%)',
      default: 'hsl(30 75% 52%)',
      darker: 'hsl(33 100% 39%)',
    },
    {
      lighter: 'hsl(46 72% 50%)',
      default: 'hsl(47 100% 38%)',
      darker: 'hsl(45 100% 33%)',
    },
    {
      lighter: 'hsl(120 48% 63%)',
      default: 'hsl(121 38% 54%)',
      darker: 'hsl(122 39% 45%)',
    },
    {
      lighter: 'hsl(172 100% 42%)',
      default: 'hsl(172 100% 37%)',
      darker: 'hsl(171 100% 32%)',
    },
    {
      lighter: 'hsl(189 100% 48%)',
      default: 'hsl(190 100% 43%)',
      darker: 'hsl(192 100% 38%)',
    },
    {
      lighter: 'hsl(208 100% 71%)',
      default: 'hsl(211 92% 65%)',
      darker: 'hsl(210 72% 55%)',
    },
    {
      lighter: 'hsl(249 100% 82%)',
      default: 'hsl(248 85% 76%)',
      darker: 'hsl(249 59% 66%)',
    },
    {
      lighter: 'hsl(295 70% 75%)',
      default: 'hsl(295 50% 66%)',
      darker: 'hsl(295 38% 56%)',
    },
    {
      lighter: 'hsl(18 30% 72%)',
      default: 'hsl(18 22% 63%)',
      darker: 'hsl(18 17% 54%)',
    },
    {
      lighter: 'hsl(0 0% 71%)',
      default: 'hsl(0 0% 62%)',
      darker: 'hsl(0 0% 53%)',
    },
  ],
  dark: [
    {
      lighter: 'hsl(340 51% 64%)',
      default: 'hsl(340 39% 55%)',
      darker: 'hsl(339 37% 46%)',
    },
    {
      lighter: 'hsl(8 57% 63%)',
      default: 'hsl(8 44% 54%)',
      darker: 'hsl(8 45% 45%)',
    },
    {
      lighter: 'hsl(28 57% 53%)',
      default: 'hsl(29 62% 43%)',
      darker: 'hsl(32 90% 32%)',
    },
    {
      lighter: 'hsl(45 58% 45%)',
      default: 'hsl(47 87% 33%)',
      darker: 'hsl(46 100% 26%)',
    },
    {
      lighter: 'hsl(120 29% 53%)',
      default: 'hsl(120 30% 44%)',
      darker: 'hsl(121 37% 35%)',
    },
    {
      lighter: 'hsl(172 82% 38%)',
      default: 'hsl(172 100% 30%)',
      darker: 'hsl(171 100% 25%)',
    },
    {
      lighter: 'hsl(189 100% 39%)',
      default: 'hsl(190 100% 34%)',
      darker: 'hsl(191 100% 29%)',
    },
    {
      lighter: 'hsl(211 67% 62%)',
      default: 'hsl(211 53% 52%)',
      darker: 'hsl(211 57% 43%)',
    },
    {
      lighter: 'hsl(247 54% 70%)',
      default: 'hsl(248 40% 61%)',
      darker: 'hsl(248 32% 52%)',
    },
    {
      lighter: 'hsl(295 35% 62%)',
      default: 'hsl(295 28% 53%)',
      darker: 'hsl(295 29% 44%)',
    },
    {
      lighter: 'hsl(18 20% 60%)',
      default: 'hsl(18 16% 51%)',
      darker: 'hsl(18 18% 42%)',
    },
    {
      lighter: 'hsl(0 0% 59%)',
      default: 'hsl(0 0% 50%)',
      darker: 'hsl(0 0% 42%)',
    },
  ],
};

export type Color = keyof typeof SPECTRUM.light;
