// generated by @/scripts/generate-theme.ts

export const SPECTRUM = {
  light: [
    {
      lighter: 'hsl(340 80% 71%)',
      default: 'hsl(339 58% 61%)',
      darker: 'hsl(338 46% 52%)',
    },
    {
      lighter: 'hsl(8 88% 69%)',
      default: 'hsl(8 65% 60%)',
      darker: 'hsl(7 51% 50%)',
    },
    {
      lighter: 'hsl(30 81% 56%)',
      default: 'hsl(32 91% 43%)',
      darker: 'hsl(31 100% 36%)',
    },
    {
      lighter: 'hsl(48 100% 40%)',
      default: 'hsl(46 100% 35%)',
      darker: 'hsl(44 100% 30%)',
    },
    {
      lighter: 'hsl(121 41% 57%)',
      default: 'hsl(121 36% 48%)',
      darker: 'hsl(123 46% 38%)',
    },
    {
      lighter: 'hsl(172 100% 38%)',
      default: 'hsl(171 100% 34%)',
      darker: 'hsl(170 100% 29%)',
    },
    {
      lighter: 'hsl(190 100% 44%)',
      default: 'hsl(191 100% 39%)',
      darker: 'hsl(192 100% 35%)',
    },
    {
      lighter: 'hsl(211 100% 67%)',
      default: 'hsl(211 78% 58%)',
      darker: 'hsl(210 69% 48%)',
    },
    {
      lighter: 'hsl(248 98% 79%)',
      default: 'hsl(249 66% 69%)',
      darker: 'hsl(249 49% 60%)',
    },
    {
      lighter: 'hsl(295 55% 69%)',
      default: 'hsl(295 41% 59%)',
      darker: 'hsl(295 33% 50%)',
    },
    {
      lighter: 'hsl(18 24% 66%)',
      default: 'hsl(18 19% 57%)',
      darker: 'hsl(18 17% 48%)',
    },
    {
      lighter: 'hsl(0 0% 65%)',
      default: 'hsl(0 0% 56%)',
      darker: 'hsl(0 0% 47%)',
    },
  ],
  dark: [
    {
      lighter: 'hsl(339 64% 65%)',
      default: 'hsl(338 49% 55%)',
      darker: 'hsl(337 48% 45%)',
    },
    {
      lighter: 'hsl(8 71% 63%)',
      default: 'hsl(7 55% 54%)',
      darker: 'hsl(7 56% 44%)',
    },
    {
      lighter: 'hsl(31 77% 48%)',
      default: 'hsl(32 100% 37%)',
      darker: 'hsl(29 100% 33%)',
    },
    {
      lighter: 'hsl(47 100% 37%)',
      default: 'hsl(45 100% 32%)',
      darker: 'hsl(43 100% 27%)',
    },
    {
      lighter: 'hsl(121 35% 51%)',
      default: 'hsl(122 42% 41%)',
      darker: 'hsl(124 58% 32%)',
    },
    {
      lighter: 'hsl(172 100% 35%)',
      default: 'hsl(171 100% 31%)',
      darker: 'hsl(170 100% 26%)',
    },
    {
      lighter: 'hsl(191 100% 41%)',
      default: 'hsl(192 100% 36%)',
      darker: 'hsl(194 100% 32%)',
    },
    {
      lighter: 'hsl(211 84% 61%)',
      default: 'hsl(210 67% 51%)',
      darker: 'hsl(208 85% 40%)',
    },
    {
      lighter: 'hsl(248 74% 73%)',
      default: 'hsl(249 54% 63%)',
      darker: 'hsl(250 42% 54%)',
    },
    {
      lighter: 'hsl(295 45% 62%)',
      default: 'hsl(295 36% 53%)',
      darker: 'hsl(295 37% 44%)',
    },
    {
      lighter: 'hsl(18 20% 60%)',
      default: 'hsl(18 16% 51%)',
      darker: 'hsl(18 18% 42%)',
    },
    {
      lighter: 'hsl(0 0% 59%)',
      default: 'hsl(0 0% 50%)',
      darker: 'hsl(0 0% 42%)',
    },
  ],
};

export type Color = keyof typeof SPECTRUM.light;
