import { COLORS } from '@/theme/base';
import { BREAKPOINTS, RADII } from '@/theme/tokens';
import { execSync } from 'child_process';
import chroma from 'chroma-js';
import fs from 'fs';
import path from 'path';
import { createLogger } from './logger';

const { log, progress } = createLogger('generate-theme');

const themePath = (...segments: string[]) =>
  path.join(__dirname, '../theme', ...segments);

function parseOKLCH(oklchStr: string): {
  l: number;
  c: number;
  h: number;
  a?: string;
} {
  const match = oklchStr.match(/oklch\(([^)]+)\)/);
  if (!match) throw new Error('Invalid OKLCH: ' + oklchStr);
  const parts = match[1].split('/').map((s) => s.trim());
  const [l, c, h] = parts[0].split(/\s+/).map(Number);
  const a = parts[1] ? parts[1] : undefined;
  return { l, c, h, a };
}

function oklchToHSLStr(oklchStr: string): string {
  const { l, c, h, a } = parseOKLCH(oklchStr);
  const hsl = chroma.oklch(l, c, h).hsl();
  let hVal = Math.round(hsl[0]);
  let sVal = Math.round(hsl[1] * 100);
  let lVal = Math.round(hsl[2] * 100);
  if (isNaN(hVal)) hVal = 0;
  if (isNaN(sVal)) sVal = 0;
  if (isNaN(lVal)) lVal = 0;

  if (sVal === 0 || lVal === 0 || lVal === 100) {
    hVal = 0;
    sVal = 0;
  }

  if (a) return `${hVal} ${sVal}% ${lVal}% / ${a}`;
  return `${hVal} ${sVal}% ${lVal}%`;
}

function genCSSVars(theme: Record<string, string>) {
  let css = '';

  for (const [key, value] of Object.entries(theme)) {
    const varName = `--${key.replace(/([A-Z])/g, '-$1').toLowerCase()}`;
    css += `${varName}:${oklchToHSLStr(value)};`;
  }

  return css;
}

function toThemeVarName(key: string) {
  return key.replace(/([A-Z])/g, '-$1').toLowerCase();
}

function generateTailwindTheme() {
  const uiTheme = Object.keys(COLORS.light.ui).map((key) => {
    const varName = toThemeVarName(key);
    return `--color-${varName}: hsl(var(--${varName}));`;
  });

  return [
    ...uiTheme,
    `--radius: ${RADII.DEFAULT};`,
    `--radius-xs: ${RADII.xs};`,
    `--radius-sm: ${RADII.sm};`,
    `--radius-md: ${RADII.md};`,
    `--radius-lg: ${RADII.lg};`,
    `--radius-xl: ${RADII.xl};`,
    `--radius-2xl: ${RADII['2xl']};`,
    `--radius-3xl: ${RADII['3xl']};`,
    `--radius-4xl: ${RADII['4xl']};`,
    `--breakpoint-2xs: ${BREAKPOINTS['2xs']};`,
    `--breakpoint-xs: ${BREAKPOINTS.xs};`,
    `--breakpoint-sm: ${BREAKPOINTS.sm};`,
    `--breakpoint-md: ${BREAKPOINTS.md};`,
    `--breakpoint-lg: ${BREAKPOINTS.lg};`,
    `--breakpoint-xl: ${BREAKPOINTS.xl};`,
    `--breakpoint-2xl: ${BREAKPOINTS['2xl']};`,
  ].join('\n  ');
}

function generateGlobalCSS() {
  const lightVars = genCSSVars(COLORS.light.ui);
  const darkVars = genCSSVars(COLORS.dark.ui);
  const theme = generateTailwindTheme();

  return `/* generated by @/scripts/generate-theme.ts */\n\n@import 'tailwindcss';\n@import 'uniwind';\n@plugin 'tailwindcss-animate';\n\n@source "../app";\n@source "../features";\n@source "../ui";\n@source "../hooks";\n\n@theme inline {\n  ${theme}\n}\n\n@layer theme {\n  :root {\n    @variant light {\n      ${lightVars}\n    }\n\n    @variant dark {\n      ${darkVars}\n    }\n  }\n}`;
}

function generateSpectrumTS() {
  function getVariants(oklchStr: string) {
    const { l, c, h } = parseOKLCH(oklchStr);

    const variants = {
      lighter: `hsl(${oklchToHSLStr(`oklch(${Math.min(l + 0.075, 1)} ${c} ${h})`)})`,
      default: `hsl(${oklchToHSLStr(oklchStr)})`,
      darker: `hsl(${oklchToHSLStr(`oklch(${Math.max(l - 0.075, 0)} ${c} ${h})`)})`,
    };

    return variants;
  }

  const spectrum: Record<string, ReturnType<typeof getVariants>[]> = {
    light: [],
    dark: [],
  };

  for (const mode of ['light', 'dark'] as const) {
    const modeColors = COLORS[mode] as typeof COLORS.light;

    for (const [key, value] of modeColors.spectrum.entries()) {
      spectrum[mode][key] = getVariants(value as string);
    }
  }

  return `// generated by @/scripts/generate-theme.ts\n\nexport const SPECTRUM=${JSON.stringify(spectrum)} as const;\n\ntype ToNumber<T>=T extends \`${'${'}infer N extends number${'}'}\` ? N : never;\ntype SpectrumIndex=Extract<keyof typeof SPECTRUM.light,\`${'${'}number${'}'}\`>;\n\nexport type Color=ToNumber<SpectrumIndex>;`;
}

function generateUITS() {
  const ui: Record<string, Record<string, string>> = {
    light: {},
    dark: {},
  };

  for (const mode of ['light', 'dark'] as const) {
    const modeColors = COLORS[mode] as typeof COLORS.light;

    for (const [key, value] of Object.entries(modeColors.ui)) {
      ui[mode][key] = `hsl(${oklchToHSLStr(value as string)})`;
    }
  }

  return `// generated by @/scripts/generate-theme.ts\n\nexport const UI=${JSON.stringify(ui)};\n\nexport type UIColor=keyof typeof UI.light;`;
}

const outputPaths = [
  {
    path: themePath('global.css'),
    render: generateGlobalCSS,
  },
  {
    path: themePath('spectrum.ts'),
    render: generateSpectrumTS,
  },
  {
    path: themePath('ui.ts'),
    render: generateUITS,
  },
] as const;

fs.mkdirSync(themePath(), { recursive: true });

log(`Writing ${outputPaths.length} theme outputs`);

for (const [index, output] of outputPaths.entries()) {
  fs.writeFileSync(output.path, output.render());
  progress(`Theme ${index + 1}/${outputPaths.length}: ${output.path}`);
}

log('Formatting generated theme files');

const prettierOutput = execSync(
  'bunx prettier --write "theme/global.css" "theme/spectrum.ts" "theme/ui.ts"',
  { encoding: 'utf8' }
);

for (const line of prettierOutput.split('\n')) {
  const trimmedLine = line.trim();

  if (trimmedLine.length > 0) {
    progress(trimmedLine);
  }
}

log('Done');
